{% set name = "eagle" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/tony-kuo/eagle.git
  git_tag: master

requirements:
  build:
    - git
    - gcc
    - make
    - zlib
    - bzip2
    - xz
    - libcurl

about:
  home: https://github.com/tony-kuo/eagle
  license: BSD
  summary: Explicit Alternative Genome Likelihood Evaluator (EAGLE)
