# This is a basic workflow adapted from the default Action worflow

name: ARPEGGIO_run

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch. Added trigger to publishhed and created 
# releases as well
on:
  push:
  pull_request:
    branches: [ master ]
  release:
    types: [ published, created ]
    

# The workflow will have three jobs: running the main ARPEGGIO mode, linting and trying additional configs
jobs:
  # Name of the job
  run-worfklow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Run default snakemake
      - uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--cores 1 --use-conda'

  run-linting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Run default snakemake
      - uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--lint'

  run-modes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Run snakemake diploid only mode paired-end reads
      - name: run-ARPEGGIO-dp-PE
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--configfile example/additional_config/config_dp_PE.yaml -n'

      # Run snakemake diploid only mode single-end reads
      - name: run-ARPEGGIO-dp-SE
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--configfile example/additional_config/config_dp_SE.yaml -n'

      # Run snakemake polyploid only mode paired-end reads
      - name: run-ARPEGGIO-pp-PE
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--configfile example/additional_config/config_pp_PE.yaml -n'

      # Run snakemake polyploid only mode single-end reads
      - name: run-ARPEGGIO-pp-SE
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '--configfile example/additional_config/config_pp_SE.yaml -n'
