# This is a basic workflow adapted from the default Action worflow

name: ARPEGGIO

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch. Added trigger to publishhed and created 
# releases as well
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published, created ]
    

# The workflow will have just one job
jobs:
  # Name of the job
  run-worfklow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      # Runs a single command using snakemake (taken from the single-cell-rna-seq snakemake repo)
      - name: ARPEGGIO-test
        uses: snakemake/snakemake-github-action@master
        with:
          snakefile: Snakefile
          args: "--use-conda --cores 1"
